name: Deploy with docker

on:
  push:
    # 分支
    branches: [ master ] 
    tags: [ v* ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to Docker Hub
        if: ${{ contains(github.ref, 'v') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Set up Docker Buildx
        if: ${{ contains(github.ref, 'v') }}
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: ${{ contains(github.ref, 'v') }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.aarch64
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.USERNAME }}/code-server:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.USERNAME }}/code-server:latest